apiVersion: v1
appVersion: 2.0.0.0-b16
version: 2.0.0
home: https://www.yugabyte.com
description: YugaWare is YugaByte Database's Orchestration and Management console.
name: yugaware
icon: https://avatars0.githubusercontent.com/u/17074854?s=200&v=4
maintainers:
- name: Ram Sri
  email: ram@yugabyte.com
