# Default values for yugaware.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: quay.io/yugabyte/yugaware
  tag: 1.2.13.0-b8  
  pullPolicy: IfNotPresent
  pullSecret: yugabyte-k8s-pull-secret

yugaware:
  replicas: 1
  storage: 100Gi
  storageClass: standard
  multiTenant: false
  serviceAccount: yugaware
  service:
    enabled: true
    ip: ""
    type: "LoadBalancer"
  health:
    username: ""
    password: ""
