{{- $root := . -}}

{{- range .Values.Services }}

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $root.Release.Name }}-{{ .name }}"
  labels:
    app: "{{ $root.Release.Name }}-{{ .label }}"
    heritage: {{ $root.Release.Service | quote }}
    release: {{ $root.Release.Name | quote }}
    chart: "{{ $root.Chart.Name }}-{{ $root.Chart.Version }}"
    component: "{{ $root.Release.Name }}-{{ $root.Values.Component }}"
spec:
  clusterIP: None
  ports:
    {{- range $label, $port := .ports }}
    - name: {{ $label | quote }}
      port: {{ $port }}
    {{- end}}
  selector:
    app: "{{ $root.Release.Name }}-{{ .label }}"

{{- if .hasLoadBalancer }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $root.Release.Name }}-{{ .label }}-ui"
  labels:
    app: "{{ $root.Release.Name }}-{{ .label }}"
    heritage: {{ $root.Release.Service | quote }}
    release: {{ $root.Release.Name | quote }}
    chart: "{{ $root.Chart.Name }}-{{ $root.Chart.Version }}"
    component: "{{ $root.Release.Name }}-{{ $root.Values.Component }}"
spec:
  clusterIP:
  ports:
    - name: ui
      port: 7000
  selector:
    app: "{{ $root.Release.Name }}-{{ .label }}"
  type: LoadBalancer
{{- end }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ $root.Release.Name }}-{{ .label }}"
  labels:
    app: "{{ $root.Release.Name }}-{{ .label }}"
    heritage: {{ $root.Release.Service | quote }}
    release: {{ $root.Release.Name | quote }}
    chart: "{{ $root.Chart.Name }}-{{ $root.Chart.Version }}"
    component: "{{ $root.Release.Name }}-{{ $root.Values.Component }}"
spec:
  serviceName: "{{ $root.Release.Name }}-{{ .name }}"
  podManagementPolicy: {{ $root.Values.PodManagementPolicy }}
  replicas: {{ .replicas }}
  volumeClaimTemplates:
    {{- range $index := until (int ($root.Values.persistentVolume.count )) }}
    - metadata:
        name: datadir{{ $index }}
        labels:
          heritage: {{ $root.Release.Service | quote }}
          release: {{ $root.Release.Name | quote }}
          chart: "{{ $root.Chart.Name }}-{{ $root.Chart.Version }}"
          component: "{{ $root.Release.Name }}-{{ $root.Values.Component }}"
      spec:
        accessModes:
          - "ReadWriteOnce"
        {{- if $root.Values.persistentVolume.storageClass }}
        storageClassName: {{ $root.Values.persistentVolume.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ $root.Values.persistentVolume.storage }}
    {{- end }}

  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: "{{ $root.Release.Name }}-{{ .label }}"
  template:
    metadata:
      labels:
        app: "{{ $root.Release.Name }}-{{ .label }}"
        heritage: {{ $root.Release.Service | quote }}
        release: {{ $root.Release.Name | quote }}
        chart: "{{ $root.Chart.Name }}-{{ $root.Chart.Version }}"
        component: "{{ $root.Release.Name }}-{{ $root.Values.Component }}"
    spec:
      {{- if $root.Values.nodeSelector }}
      nodeSelector:
      {{ toYaml $root.Values.nodeSelector | indent 8 }}
      {{- end }}
      affinity:
        # Set the anti-affinity selector scope to YB masters.
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - "{{ $root.Release.Name }}-{{ .label }}"
              topologyKey: kubernetes.io/hostname
      containers:
      - name: "{{ $root.Release.Name }}-{{ .label }}"
        image: "{{ $root.Values.Image.repository }}:{{ $root.Values.Image.tag }}"
        imagePullPolicy: {{ $root.Values.Image.pullPolicy }}
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        metadata:
          labels:
            heritage: {{ $root.Release.Service | quote }}
            release: {{ $root.Release.Name | quote }}
            chart: "{{ $root.Chart.Name }}-{{ $root.Chart.Version }}"
            component: "{{ $root.Release.Name }}-{{ $root.Values.Component }}"
        command:
        {{ if eq .name "yb-masters" }}
          - "/home/yugabyte/bin/yb-master"
          - "--fs_data_dirs={{range $index := until (int ($root.Values.persistentVolume.count))}}{{if ne $index 0}},{{end}}/mnt/disk{{ $index }}{{end}}"
          - "--rpc_bind_addresses=$(POD_IP)"
          - "--master_addresses={{ $root.Release.Name }}-yb-masters:7100"
          - "--master_replication_factor={{ .replicas }}"
        {{ else }}
          - "/home/yugabyte/bin/yb-tserver"
          - "--fs_data_dirs={{range $index := until (int ($root.Values.persistentVolume.count))}}{{if ne $index 0}},{{end}}/mnt/disk{{ $index }}{{end}}"
          - "--tserver_master_addrs={{ $root.Release.Name }}-yb-masters:7100"
          - "--tserver_master_replication_factor={{ .replicas }}"
        {{ end }}
        ports:
          {{- range $label, $port := .ports }}
          - containerPort: {{ $port }}
            name: {{ $label | quote }}
          {{- end}}
        volumeMounts:
          {{- range $index := until (int ($root.Values.persistentVolume.count)) }}
          - name: datadir{{ $index }}
            mountPath: /mnt/disk{{ $index }}
          {{- end }}
      volumes:
        {{- range $index := until (int ($root.Values.persistentVolume.count)) }}
        - name: datadir{{ $index }}
          hostPath:
            path: /mnt/disks/ssd{{ $index }}
        {{- end }}
{{- end }}
