# Default values for yugabyte.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
Component: "yugabytedb"
Image:
  repository: "yugabytedb/yugabyte"
  tag: latest
  pullPolicy: IfNotPresent

storage:
  master:
    count: 2
    size: 10Gi
    storageClass: standard
  tserver:
    count: 2
    size: 10Gi
    storageClass: standard

resource:
  master:
    requests:
      cpu: 2
      memory: 2Gi
    limits:
      cpu: 2
      memory: 2Gi
  tserver:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 2
      memory: 4Gi

replicas:
  master: 3
  tserver: 3

partition:
  master: 0
  tserver: 0

gflags:
  master:
    default_memory_limit_to_ram_ratio: 0.85
  tserver:
    use_cassandra_authentication: False

PodManagementPolicy: Parallel

# Flag to use to enable postgres support on tservers.
# enablePostgres: false

enableLoadBalancer: True

serviceEndpoints:
  - name: "yb-master-ui"
    type: LoadBalancer
    app: "yb-master"
    ports:
      ui: "7000"

Services:
  - name: "yb-masters"
    label: "yb-master"
    memory_limit_to_ram_ratio: 0.85
    ports:
      ui: "7000"
      rpc-port: "7100"

  - name: "yb-tservers"
    label: "yb-tserver"
    ports:
      ui: "9000"
      rpc-port: "7100"
      yql-port: "9042"
      yedis-port: "6379"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
