{{- if .Values.image.pullSecretCredential -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.pullSecret }}
  labels:
    app: {{ template "yugaware.name" . }}
    chart: {{ template "yugaware.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.image.pullSecretCredential }}
{{- end -}}
